= cross-make-linux
:icons: font
:source-highlighter: rouge

`cross-make-linux` is a shim to directly compile the linux kernel on macOS. No
virtual machine or docker image is required.

* It ensures the required set of gnu binaries (e.g. `find`, `gmake`, `gsed`,
  etc.) are used by kbuild.

* It prepend values to `HOSTCFLAGS` and related variables when invoking make so
  that the HOST helper executables can build and run (thos in linux/scripts/*).


== Install

[source,bash]
----
brew install archie2x/cross/cross-make-linux
----

== Example

You will also need a working cross compiler setup. For example:

[source,bash]
----
brew install llvm lld
----

Assuming the cross-compilers are setup (here llvm/clang), here's an
example of building the Raspberry Pi 5 kernel, device tree, and modules.

----
export ARCH=arm64 LLVM=1
linux > cross-make-linux O=build -j$(nproc) bcm2712_defconfig
linux > cross-make-linux O=build -j$(nproc) Image.gz modules dtbs
linux > cross-make-linux O=build -j$(nproc) INSTALL_MOD_PATH=dist modules_install
----

== Caveats

Linux kernel builds require a case-sensitive filesystem. and a helper script is
bundled to create a APFS case-sensitive volume:

[source,bash]
----
sudo $(brew --prefix cross-make-linux)/libexec/bin/create-case-sensitive.sh
----

You’ll likely only need to run it once. It creates an APFS case-sensitive volume
named `case-sensitive` and mounts it at `/Volumes/case-sensitive`.

For my personal workflow (recommended 😎), I mount it at `~/src` and do all my
development work / git checkouts in that directory.

Example:
----
> sudo $(brew --prefix cross-make-linux)//bin/create-case-sensitive.sh NAME MOUNT
> cd MOUNT
> git clone --depth=1 -b rpi-6.12.y https://github.com/raspberrypi/linux
> cd linux
> cross-make-linux ...
----

This can also be done manually via the `disk-utility` application though I'm
only aware of CLI tools to mount it at a custom location.

== Acknowledgements

The following resources were helpful in figuring out the details.

* https://seiya.me/blog/building-linux-on-macos-natively
* https://stackoverflow.com/questions/10018764/building-linux-kernel-on-mac-os-x/61707998#61707998

== License

SPDX-License-Identifier: MIT
