= cross-make-linux
:icons: font
:source-highlighter: rouge

`cross-make-linux` is a shim to directly compile the linux kernel on macOS
without using a virtual machine or docker image.

* It ensures the required set of gnu binaries (e.g. `find`, `gmake`, `gsed`,
  etc.) are used by kbuild.

* It prepend values to `HOSTCFLAGS` and related variables when invoking make so
  that the HOST helper executables can build and run (scripts/*).

Roger Standridge <archie2x@users.noreply.github.com>

== Install

Via homebrew (recommended):
[source,bash]
----
brew install archie2x/cross/cross-make-linux
----

Git clone:
[source, bash]
----
git clone git@github.com:archie2x/cross-make-linux
PATH="$PWD/cross-make-linux/bin:$PATH"
----

== Example

You will also need a working cross compiler setup. For example:

[source,bash]
----
brew install llvm lld
----

Assuming the cross-compilers are setup, and assuming here llvm/clang, here's an
example of building the Raspberry Pi 5 kernel, device tree, and modules.

[source,bash]
----
linux > cross-make-linux LLVM=1 ARCH=arm64 O=build bcm2712_defconfig
linux > cross-make-linux LLVM=1 ARCH=arm64 O=build Image.gz modules dtbs
linux > cross-make-linux LLVM=1 ARCH=arm64 O=build INSTALL_MOD_PATH=dist modules_install
----

== Caveat

Linux kernel builds require a case-sensitive filesystem.

A helper script is bundled to create a APFS case-sensitive volume:

[source,bash]
----
$(brew --prefix cross-make-linux)/libexec/bin/create-case-sensitive.sh
----

You’ll likely only need to run it once.

Example:
----
> bash $(brew --prefix cross-make-linux)//bin/create-case-sensitive.sh NAME MOUNT
> cd MOUNT
> git clone --depth=1 -b rpi-6.12.y https://github.com/raspberrypi/linux
> cd linux
> cross-make-linux ...
----

== Acknowledgements

https://seiya.me/blog/building-linux-on-macos-natively
https://stackoverflow.com/questions/10018764/building-linux-kernel-on-mac-os-x/61707998#61707998

== License

SPDX-License-Identifier: MIT
