= cross-make-linux
:icons: font
:source-highlighter: rouge

`cross-make-linux` is a shim to directly compile the linux kernel on macOS. No
virtual machine or docker image is required.

* It ensures the required set of gnu binaries (e.g. `find`, `gmake`, `gsed`,
  etc.) are used by kbuild.

* It prepend values to `HOSTCFLAGS` and related variables when invoking make so
  that the HOST helper executables can build and run (thos in linux/scripts/*).


== Install

[source,bash]
----
brew install archie2x/cross/cross-make-linux
----

== Example

You will also need a working cross compiler setup.

[source,bash]
----
brew install llvm lld
PATH="$(brew prefix llvm)/bin:$PATH"
----

Assuming the cross-compilers are setup (here llvm/clang), here's an
example of building the Raspberry Pi 5 kernel, device tree, and modules.

----
export ARCH=arm64 LLVM=1
linux > cross-make-linux O=build -j$(nproc) bcm2712_defconfig
linux > cross-make-linux O=build -j$(nproc) Image.gz modules dtbs
linux > cross-make-linux O=build -j$(nproc) INSTALL_MOD_PATH=dist modules_install
----

== Caveats

Linux kernel builds require a case-sensitive filesystem. You can create one with
the `disk-utility` application. I'm only aware, however, of CLI tools to mount
it at a custom location.

A helper script is bundled to create and mount an APFS case-sensitive volume at
a custom location. You’ll likely only need to run it once. By default the volume
will be named `case-sensitive` and mounted at `/Volumes/case-sensitive`. The
name and mount location can be overridden by arguments to the script.

[source,bash]
----
sudo $(brew --prefix cross-make-linux)/libexec/bin/create-case-sensitive.sh
----

For my personal workflow (recommended 😎), I mount it at `~/src` and do all my
development work / git checkouts in that directory.

Example:
----
> sudo $(brew --prefix cross-make-linux)/bin/create-case-sensitive.sh case-sensitive ~/src
> git clone --depth=1 -b rpi-6.12.y https://github.com/raspberrypi/linux ~/src/linux
> cd ~/src/linux
> cross-make-linux ...
----

== Acknowledgements

* https://seiya.me/blog/building-linux-on-macos-natively
* https://stackoverflow.com/questions/10018764/building-linux-kernel-on-mac-os-x/61707998#61707998
* https://mastermakrela.com/kernel/lkp/kernel-dev-on-macos

== License

SPDX-License-Identifier: MIT
